DROP TABLE IF EXISTS stats;

CREATE TABLE stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    timestamp INTEGER NOT NULL,
    probe TEXT NOT NULL,
    metric REAL NOT NULL
);